// import { fromJSON } from 'postcss'

export {default as About} from './about/About'
export {default as GetStarted} from  './getStarted/GetStarted'
export {default as Home} from './home/Home'
export {default as SignIn} from './signIn/SignIn'
export {default as SignUp} from './signUp/SignUp'
export {default as Dhashboard} from './TenateDhashboard/Dhashboard'
export {default as Properties} from './TenateDhashboard/Properties'
export {default as Dashboard} from './LanDashboard/Dashboard'
export {default as Tenants} from './LanDashboard/Tenants'
export {default as Requests} from './LanDashboard/Requests'
export {default as AddProperty} from './LanDashboard/AddProperty'
export {default as MyProperties} from './LanDashboard/Properties'
export {default as ViewProperty} from './TenateDhashboard/ViewProperty'
export {default as SignUpB} from './SignUpBusines/SignUp'
export {default as EditProperty} from './LanDashboard/EditProperty'
export {default as Profile} from './TenateDhashboard/Profile'
export {default as EditProfile} from './TenateDhashboard/EditProfile'
export {default as MyProfile} from './LanDashboard/Profile'
export {default as LanEditProfile} from './LanDashboard/EditProfile'
